=== knorby/pyxsd/tests/fixtures/datatypes/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="when" type="xs:date"/>
        <xs:element name="moment" type="xs:dateTime"/>
        <xs:element name="alarm" type="xs:time"/>
        <xs:element name="span" type="xs:duration"/>
        <xs:element name="price" type="xs:decimal"/>
        <xs:element name="checksum" type="xs:hexBinary"/>
        <xs:element name="population" type="xs:long"/>
        <xs:element name="offset" type="xs:int"/>
        <xs:element name="level" type="xs:short"/>
        <xs:element name="code" type="xs:byte"/>
        <xs:element name="quantity" type="xs:unsignedByte"/>
        <xs:element name="website" type="xs:anyURI"/>
        <xs:element name="debt" type="xs:negativeInteger"/>
        <xs:element name="year" type="xs:gYear"/>
        <xs:element name="title" type="xs:token"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== knorby/pyxsd/tests/fixtures/datatypes/instance.xml
<?xml version="1.0"?>
<record xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
  <when>2006-08-30</when>
  <moment>2006-08-30T14:30:00</moment>
  <alarm>09:00:00</alarm>
  <span>P1Y2M3D</span>
  <price>19.95</price>
  <checksum>00FF10</checksum>
  <population>6700000000</population>
  <offset>42</offset>
  <level>7</level>
  <code>120</code>
  <quantity>200</quantity>
  <website>https://example.com/data</website>
  <debt>-500</debt>
  <year>2006</year>
  <title>sample record</title>
</record>
