=== knorby/pyxsd/examples/demo/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="colorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="red"/>
      <xs:enumeration value="green"/>
      <xs:enumeration value="blue"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="itemType">
    <xs:annotation>
      <xs:documentation>An item in the inventory.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="quantity" type="xs:integer"/>
      <xs:element name="color" type="colorType"/>
      <xs:element name="note" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:element name="inventory">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== knorby/pyxsd/examples/demo/instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventory
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd">
  <item id="a1">
    <name>wrench</name>
    <quantity>12</quantity>
    <color>red</color>
  </item>
  <item id="a2">
    <name>hammer</name>
    <quantity>3</quantity>
    <color>blue</color>
    <note>handle broken</note>
  </item>
</inventory>
